#version 450

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = vec2(pixel) / vec2(imageSize(outputImage));

    vec3 color = vec3(
        uv.x,
        uv.y,
        0.5
    );

    imageStore(
        outputImage,
        pixel,
        vec4(color, 1.0)
    );
}